MDScreen:
    name: "login"
    MDFloatLayout:
        md_bg_color: 76/255, 0, 48/255, 1
        MDIconButton:
            icon: "chevron-left"
            user_font_size: "35sp"
            pos_hint: {"center_y": .95}
        MDLabel:
            text: "Back"
            font_size: "18sp"
            font_name: "Roboto-Regular"
            pos_hint: {"center_x": .615, "center_y": .949}
            