MDScreen:
    MDBoxLayout:
        size_hint_y: .25
        
        MDBoxLayout:
            orientation: 'vertical'
            MDLabel:
                text: "Dashboard"
                
            MDBoxLayout:
                adaptive_size: True
                MDLabel:
                    text: "none"
                    text_size: None, None
                MDIcon:
                    icon: "chevron-down"

